from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.common.exceptions import TimeoutException
import pyautogui
from selenium import webdriver
from webdriver_manager.firefox import GeckoDriverManager
from selenium.webdriver.common.keys import Keys
import time
from selenium.webdriver.support.ui import WebDriverWait
import datetime
import os
import shutil
import random

def uploadvideo(video,subs,title,description,thumbnail):
    driver = webdriver.Chrome("/usr/lib/chromium-browser/chromedriver")
    # driver.get("https://accounts.google.com/signin/v2/identifier?service=youtube&uilel=3&passive=true&continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26hl%3Den%26next%3Dhttps%253A%252F%252Fwww.youtube.com%252F&hl=en&ec=65620&flowName=GlifWebSignIn&flowEntry=ServiceLogin")
    # time.sleep(1)
    # pyautogui.write("wikiaudiayt@gmail.com", interval=0.1)
    # pyautogui.moveTo(622, 775, 0.5)
    # pyautogui.click()
    # time.sleep(2)
    # pyautogui.write("w1k1p3d1a12345!@#$%", interval=0.2)
    # pyautogui.moveTo(626, 679, 0.5)
    # pyautogui.click()
    # time.sleep(1)
    driver.get("https://studio.youtube.com/channel/UCsLCKPmJXsDh90Eum8eMZXw/videos/upload?d=ud&filter=%5B%5D&sort=%7B%22columnType%22%3A%22date%22%2C%22sortOrder%22%3A%22DESCENDING%22%7D")
    time.sleep(1)
    pyautogui.write("wikiaudiayt@gmail.com", interval=0.1)
    pyautogui.moveTo(622, 775, 0.5)
    pyautogui.click()
    time.sleep(2)
    pyautogui.write("w1k1p3d1a12345!@#$%", interval=0.2)
    pyautogui.moveTo(626, 679, 0.5)
    pyautogui.click()
    time.sleep(5)
    # pyautogui.moveTo(820, 195, 0.5)
    # pyautogui.click()
    # pyautogui.moveTo(793, 243, 0.5)
    # pyautogui.click()
    pyautogui.moveTo(481, 731, 0.5)
    pyautogui.click()
    pyautogui.moveTo(1134, 103, 0.5)
    pyautogui.click()
    pyautogui.write("WikiAudia", interval=0.2)
    time.sleep(0.5)
    pyautogui.press(['enter'])
    pyautogui.moveTo(1134, 103, 0.5)
    pyautogui.click()
    pyautogui.write(video, interval=0.2)
    time.sleep(0.5)
    pyautogui.press(['enter'])
    time.sleep(10)
    pyautogui.write(title)
    pyautogui.press(['enter'])
    time.sleep(1)
    pyautogui.moveTo(570, 702, 0.5)
    pyautogui.scroll(-100)
    pyautogui.moveTo(60, 782, 0.5)
    pyautogui.click()
    pyautogui.moveTo(95, 901, 0.5)
    pyautogui.click()
    pyautogui.scroll(-12)
    pyautogui.moveTo(214, 680, 0.5)
    pyautogui.click()
    time.sleep(1)
    for i in range(26):
        pyautogui.press(['down'])
        time.sleep(0.1)
    pyautogui.moveTo(93, 552, 0.5)
    pyautogui.click()
    pyautogui.moveTo(143, 740, 0.5)
    pyautogui.click()
    pyautogui.moveTo(570, 702, 0.5)
    pyautogui.click()
    pyautogui.moveTo(1134, 103, 0.5)
    pyautogui.click()
    pyautogui.write(subs, interval=0.2)
    time.sleep(0.5)
    pyautogui.press(['enter'])
    time.sleep(0.5)
    pyautogui.moveTo(570, 702, 0.5)
    pyautogui.scroll(300)
    pyautogui.moveTo(119,789,0.5)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.moveTo(1134, 103, 0.5)
    pyautogui.click()
    pyautogui.write(thumbnail, interval=0.2)
    pyautogui.press(['enter'])
    time.sleep(0.5)
    pyautogui.moveTo(570, 702, 0.5)
    pyautogui.scroll(300)
    pyautogui.moveTo(91, 547, 0.5)
    pyautogui.click()
    time.sleep(1)
    pyautogui.click()
    pyautogui.write(description, interval=0.1)
    time.sleep(1)
    pyautogui.moveTo(918,991,0.5)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.moveTo(110,510,0.5)
    pyautogui.click()
    # PUBLIC: pyautogui.moveTo(110,626,0.5)
    pyautogui.moveTo(918,991,0.5)
    pyautogui.click()
    time.sleep(5)
    driver.quit()